| flngdockey                 | bigint        |         |
| fcurfdpopeningbalance      | decimal(24,4) |         |
| fcurfdppaid                | decimal(24,4) |         |
| fcurfdpcreditsrec          | decimal(24,4) |         |
| fcurfdptotalcredits        | decimal(24,4) |         |
| fcurfdpcreditspaid         | decimal(24,4) |         |
| fcurfdprefunded            | decimal(24,4) |         |
| fcurfdpotherdebits         | decimal(24,4) |         |
| fcurfdptotaldebits         | decimal(24,4) |         |
| fcurfdptotalbalance        | decimal(24,4) |         |
| fcurfdptransfer            | decimal(24,4) |         |
| fcurfdpclosingbalance      | decimal(24,4) |         |
| fcurfdpimppenaltytax       | decimal(24,4) |         |
| fcurfdptotalpayable        | decimal(24,4) |         |
| fstrwho                    | varchar(20)   |         |
| effective_from             | timestamp     |         |
| effective_to               | timestamp     |         |
| current_rec_flag           | varchar(2)    |         |
| docsetkey                  | bigint        |         |
| record_effective_timestamp | timestamp     |         |
| record_expiry_timestamp    | timestamp     |         |
| record_active_flag         | varchar(1)    |         |
| record_deleted_flag        | varchar(1)    |         |
| insert_object_run_key      | int           |         |
| update_object_run_key      | int           |         |
