create table prod_jnl_app_tblnz_rtnkssgvc_20201218 like prod_jnl.app_tblnz_rtnkssgvc;
create table prod_jnl_app_tblnz_accksfinfo_20201218 like prod_jnl.app_tblnz_accksfinfo;
create table prod_jnl_app_tblnz_ksb2bgvcclaiminb_20201218 like prod_jnl.app_tblnz_ksb2bgvcclaiminb;
