create table prod_raw_app_tblnz_rtnkssgvc_20201218 like prod_raw.app_tblnz_rtnkssgvc;
create table prod_raw_app_tblnz_accksfinfo_20201218 like prod_raw.app_tblnz_accksfinfo;
create table prod_raw_app_tblnz_ksb2bgvcclaiminb_20201218 like prod_raw.app_tblnz_ksb2bgvcclaiminb;
