CREATE TABLE dev_raw.app_tblperiodbillitem_lq (
  flngbillitemkey INT,
  flngver INT,
  flngverlast INT,
  flngaccountkey INT,
  fdtmfilingperiod TIMESTAMP,
  fintbillitem SMALLINT,
  fstrbilltype VARCHAR(12),
  fdtmcreated TIMESTAMP,
  fdtmdue TIMESTAMP,
  fstrstage VARCHAR(12),
  fdtmstaged TIMESTAMP,
  fstrpriorstage VARCHAR(12),
  fdtmpriorstaged TIMESTAMP,
  fdtmnextstageeval TIMESTAMP,
  fdtmclosed TIMESTAMP,
  fdtmprotest TIMESTAMP,
  fdtmfinalized TIMESTAMP,
  fcurtax DECIMAL(19,4),
  fcurtaxbalance DECIMAL(19,4),
  fcurtaxdelta DECIMAL(19,4),
  fcurinterest DECIMAL(19,4),
  fcurinterestbalance DECIMAL(19,4),
  fcurinterestdelta DECIMAL(19,4),
  fcurpenalty DECIMAL(19,4),
  fcurpenaltybalance DECIMAL(19,4),
  fcurpenaltydelta DECIMAL(19,4),
  fcurother DECIMAL(19,4),
  fcurotherbalance DECIMAL(19,4),
  fcurotherdelta DECIMAL(19,4),
  fcurcredit DECIMAL(19,4),
  fcurcreditdelta DECIMAL(19,4),
  fcurbalance DECIMAL(19,4),
  fdtmbillactivity TIMESTAMP,
  fdtmpenalty TIMESTAMP,
  fdtmdelta TIMESTAMP,
  flngcollectkey INT,
  finttransactioncount SMALLINT,
  fstrwho VARCHAR(20),
  fdtmwhen TIMESTAMP,
  batch_key INT
)
STORED AS PARQUET
;
