/**************************************************************************** 
 * Job:             app_tblcustomerstd P2H2               A5IKCEC7.BR000015 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: ird10119au.vsp.sas.com                                  * 
 * Port:            8561                                                    * 
 * Location:        /IRD/DIP Data Management/5000 Processes/10 Raw          * 
 *                   Ingestion                                              * 
 *                                                                          * 
 * Server:          SASApp                                A5IKCEC7.AS000002 * 
 *                                                                          * 
 * Source Table:    tblCustomerSTD -                      A5IKCEC7.BE00002B * 
 *                   strapp.tblCustomerSTD                                  * 
 * Target Table:    app_tblcustomerstd -                  A5IKCEC7.BE00001B * 
 *                   impraw.app_tblcustomerstd                              * 
 *                                                                          * 
 * Generated on:    Wednesday, October 30, 2019 3:45:27 PM NZDT             * 
 * Generated by:    ird0nxa                                                 * 
 * Version:         SAS Data Integration Studio 4.903                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5IKCEC7.BR000015);
%let etls_jobName = %nrquote(app_tblcustomerstd P2H2);
%let etls_userID = %nrquote(ird0nxa);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Change Extract                        A5IKCEC7.BT00009W * 
 * Transform:       Change Extract                                          * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    tblCustomerSTD -                      A5IKCEC7.BE00002B * 
 *                   strapp.tblCustomerSTD                                  * 
 * Target Table:    app_tblcustomerstd -                  A5IKCEC7.BE00001B * 
 *                   impraw.app_tblcustomerstd                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5IKCEC7.BT00009W);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for START GTAPP (strapp)  */ 
LIBNAME strapp SQLSVR  PRESERVE_TAB_NAMES=YES  DBMAX_TEXT=32767  PRESERVE_COL_NAMES=YES  Datasrc=NZO_GTAPP  SCHEMA=dbo  AUTHDOMAIN="start_operations" ;
%rcSet(&syslibrc); 

/* Access the data for DIP Impala RAW (impraw)  */ 
LIBNAME impraw SASIOIMP  DATABASE=dev_raw  DBMAX_TEXT=32767  DSN=ClouderaImpala64  SCHEMA=dev_raw ;
%rcSet(&syslibrc); 

%let SYSLAST = %nrquote(strapp.tblCustomerSTD); 

%let _INPUT_count = 1; 
%let _INPUT = strapp.tblCustomerSTD;
%let _INPUT_connect =  DBMAX_TEXT=32767 DATASRC=NZO_GTAPP AUTHDOMAIN="start_operations" 
;
%let _INPUT_engine = SQLSVR;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/START/START GTAPP/tblCustomerSTD%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _Source = strapp.tblCustomerSTD;
%let _Source_connect =  DBMAX_TEXT=32767 DATASRC=NZO_GTAPP AUTHDOMAIN="start_operations" 
;
%let _Source_engine = SQLSVR;
%let _Source_memtype = DATA;
%let _Source_options = %nrquote();
%let _Source_alter = %nrquote();
%let _Source_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/START/START GTAPP/tblCustomerSTD%(Table%));
%let _Source_type = 1;
%let _Source_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = impraw.app_tblcustomerstd;
%let _OUTPUT_connect =  DBMAX_TEXT=32767 DATABASE=dev_raw DSN=ClouderaImpala64
;
%let _OUTPUT_engine = SASIOIMP;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP Impala Raw/app_tblcustomerstd%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = flngdockey fdtmdob fdtmdod fstrwho fdtmwhen record_effective_timestamp 
        record_expiry_timestamp record_active_flag record_deleted_flag 
        insert_object_run_key update_object_run_key;
%let _OUTPUT_col_count = 11;
%let _OUTPUT_col0_name = flngdockey;
%let _OUTPUT_col0_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = ;
%let _OUTPUT_col0_informat = ;
%let _OUTPUT_col0_label = %nrquote(flngdockey);
%let _OUTPUT_col0_input0 = FLNGDOCKEY;
%let _OUTPUT_col0_input0_table = strapp.tblCustomerSTD;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = FLNGDOCKEY;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = fdtmdob;
%let _OUTPUT_col1_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col1_length = 8;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = datetime22.3;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(fdtmdob);
%let _OUTPUT_col1_input0 = FDTMDOB;
%let _OUTPUT_col1_input0_table = strapp.tblCustomerSTD;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = FDTMDOB;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = fdtmdod;
%let _OUTPUT_col2_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = datetime22.3;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(fdtmdod);
%let _OUTPUT_col2_input0 = FDTMDOD;
%let _OUTPUT_col2_input0_table = strapp.tblCustomerSTD;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = FDTMDOD;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = fstrwho;
%let _OUTPUT_col3_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col3_length = 20;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(fstrwho);
%let _OUTPUT_col3_input0 = FSTRWHO;
%let _OUTPUT_col3_input0_table = strapp.tblCustomerSTD;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = FSTRWHO;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = fdtmwhen;
%let _OUTPUT_col4_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = datetime22.3;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(fdtmwhen);
%let _OUTPUT_col4_input0 = FDTMWHEN;
%let _OUTPUT_col4_input0_table = strapp.tblCustomerSTD;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = FDTMWHEN;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = record_effective_timestamp;
%let _OUTPUT_col5_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col5_length = 8;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = datetime22.3;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(record_effective_timestamp);
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input_count = 0;
%let _OUTPUT_col6_name = record_expiry_timestamp;
%let _OUTPUT_col6_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col6_length = 8;
%let _OUTPUT_col6_type = ;
%let _OUTPUT_col6_format = datetime22.3;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(record_expiry_timestamp);
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input_count = 0;
%let _OUTPUT_col7_name = record_active_flag;
%let _OUTPUT_col7_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col7_length = 1;
%let _OUTPUT_col7_type = $;
%let _OUTPUT_col7_format = ;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(record_active_flag);
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input_count = 0;
%let _OUTPUT_col8_name = record_deleted_flag;
%let _OUTPUT_col8_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col8_length = 1;
%let _OUTPUT_col8_type = $;
%let _OUTPUT_col8_format = ;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(record_deleted_flag);
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input_count = 0;
%let _OUTPUT_col9_name = insert_object_run_key;
%let _OUTPUT_col9_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col9_length = 8;
%let _OUTPUT_col9_type = ;
%let _OUTPUT_col9_format = ;
%let _OUTPUT_col9_informat = ;
%let _OUTPUT_col9_label = %nrquote(insert_object_run_key);
%let _OUTPUT_col9_exp = ;
%let _OUTPUT_col9_input_count = 0;
%let _OUTPUT_col10_name = update_object_run_key;
%let _OUTPUT_col10_table = impraw.app_tblcustomerstd;
%let _OUTPUT_col10_length = 8;
%let _OUTPUT_col10_type = ;
%let _OUTPUT_col10_format = ;
%let _OUTPUT_col10_informat = ;
%let _OUTPUT_col10_label = %nrquote(update_object_run_key);
%let _OUTPUT_col10_exp = ;
%let _OUTPUT_col10_input_count = 0;

%let _target = impraw.app_tblcustomerstd;
%let _target_connect =  DBMAX_TEXT=32767 DATABASE=dev_raw DSN=ClouderaImpala64
;
%let _target_engine = SASIOIMP;
%let _target_memtype = DATA;
%let _target_options = %nrquote();
%let _target_alter = %nrquote();
%let _target_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP Impala Raw/app_tblcustomerstd%(Table%));
%let _target_type = 1;
%let _target_label = %nrquote();
/* List of target columns to keep  */ 
%let _target_keep = flngdockey fdtmdob fdtmdod fstrwho fdtmwhen record_effective_timestamp 
        record_expiry_timestamp record_active_flag record_deleted_flag 
        insert_object_run_key update_object_run_key;
%let _target_col_count = 11;
%let _target_col0_name = flngdockey;
%let _target_col0_table = impraw.app_tblcustomerstd;
%let _target_col0_length = 8;
%let _target_col0_type = ;
%let _target_col0_format = ;
%let _target_col0_informat = ;
%let _target_col0_label = %nrquote(flngdockey);
%let _target_col0_input0 = FLNGDOCKEY;
%let _target_col0_input0_table = strapp.tblCustomerSTD;
%let _target_col0_exp = ;
%let _target_col0_input = FLNGDOCKEY;
%let _target_col0_input_count = 1;
%let _target_col1_name = fdtmdob;
%let _target_col1_table = impraw.app_tblcustomerstd;
%let _target_col1_length = 8;
%let _target_col1_type = ;
%let _target_col1_format = datetime22.3;
%let _target_col1_informat = ;
%let _target_col1_label = %nrquote(fdtmdob);
%let _target_col1_input0 = FDTMDOB;
%let _target_col1_input0_table = strapp.tblCustomerSTD;
%let _target_col1_exp = ;
%let _target_col1_input = FDTMDOB;
%let _target_col1_input_count = 1;
%let _target_col2_name = fdtmdod;
%let _target_col2_table = impraw.app_tblcustomerstd;
%let _target_col2_length = 8;
%let _target_col2_type = ;
%let _target_col2_format = datetime22.3;
%let _target_col2_informat = ;
%let _target_col2_label = %nrquote(fdtmdod);
%let _target_col2_input0 = FDTMDOD;
%let _target_col2_input0_table = strapp.tblCustomerSTD;
%let _target_col2_exp = ;
%let _target_col2_input = FDTMDOD;
%let _target_col2_input_count = 1;
%let _target_col3_name = fstrwho;
%let _target_col3_table = impraw.app_tblcustomerstd;
%let _target_col3_length = 20;
%let _target_col3_type = $;
%let _target_col3_format = ;
%let _target_col3_informat = ;
%let _target_col3_label = %nrquote(fstrwho);
%let _target_col3_input0 = FSTRWHO;
%let _target_col3_input0_table = strapp.tblCustomerSTD;
%let _target_col3_exp = ;
%let _target_col3_input = FSTRWHO;
%let _target_col3_input_count = 1;
%let _target_col4_name = fdtmwhen;
%let _target_col4_table = impraw.app_tblcustomerstd;
%let _target_col4_length = 8;
%let _target_col4_type = ;
%let _target_col4_format = datetime22.3;
%let _target_col4_informat = ;
%let _target_col4_label = %nrquote(fdtmwhen);
%let _target_col4_input0 = FDTMWHEN;
%let _target_col4_input0_table = strapp.tblCustomerSTD;
%let _target_col4_exp = ;
%let _target_col4_input = FDTMWHEN;
%let _target_col4_input_count = 1;
%let _target_col5_name = record_effective_timestamp;
%let _target_col5_table = impraw.app_tblcustomerstd;
%let _target_col5_length = 8;
%let _target_col5_type = ;
%let _target_col5_format = datetime22.3;
%let _target_col5_informat = ;
%let _target_col5_label = %nrquote(record_effective_timestamp);
%let _target_col5_exp = ;
%let _target_col5_input_count = 0;
%let _target_col6_name = record_expiry_timestamp;
%let _target_col6_table = impraw.app_tblcustomerstd;
%let _target_col6_length = 8;
%let _target_col6_type = ;
%let _target_col6_format = datetime22.3;
%let _target_col6_informat = ;
%let _target_col6_label = %nrquote(record_expiry_timestamp);
%let _target_col6_exp = ;
%let _target_col6_input_count = 0;
%let _target_col7_name = record_active_flag;
%let _target_col7_table = impraw.app_tblcustomerstd;
%let _target_col7_length = 1;
%let _target_col7_type = $;
%let _target_col7_format = ;
%let _target_col7_informat = ;
%let _target_col7_label = %nrquote(record_active_flag);
%let _target_col7_exp = ;
%let _target_col7_input_count = 0;
%let _target_col8_name = record_deleted_flag;
%let _target_col8_table = impraw.app_tblcustomerstd;
%let _target_col8_length = 1;
%let _target_col8_type = $;
%let _target_col8_format = ;
%let _target_col8_informat = ;
%let _target_col8_label = %nrquote(record_deleted_flag);
%let _target_col8_exp = ;
%let _target_col8_input_count = 0;
%let _target_col9_name = insert_object_run_key;
%let _target_col9_table = impraw.app_tblcustomerstd;
%let _target_col9_length = 8;
%let _target_col9_type = ;
%let _target_col9_format = ;
%let _target_col9_informat = ;
%let _target_col9_label = %nrquote(insert_object_run_key);
%let _target_col9_exp = ;
%let _target_col9_input_count = 0;
%let _target_col10_name = update_object_run_key;
%let _target_col10_table = impraw.app_tblcustomerstd;
%let _target_col10_length = 8;
%let _target_col10_type = ;
%let _target_col10_format = ;
%let _target_col10_informat = ;
%let _target_col10_label = %nrquote(update_object_run_key);
%let _target_col10_exp = ;
%let _target_col10_input_count = 0;


%let ep_key_cols = flngdockey;
%let ep_key_cols_count = 1;
%let ep_key_cols0 = 1;
%let ep_key_cols1 = flngdockey;
%let where = ;
%let change_capture_timestamp = FDTMWHEN;
%let change_capture_timestamp_count = 1;
%let change_capture_timestamp0 = 1;
%let change_capture_timestamp1 = FDTMWHEN;
%let history_type = %nrquote(H2);
%let duplication_grain = %nrquote(1);
%let h2_effective_column = FDTMWHEN;
%let h2_effective_column_count = 1;
%let h2_effective_column0 = 1;
%let h2_effective_column1 = FDTMWHEN;
%let effective_column = fdtmwhen;
%let effective_column_count = 1;
%let effective_column0 = 1;
%let effective_column1 = fdtmwhen;
%let to_timestamp = ;
%let to_timestamp_count = 0;
%let to_timestamp0 = 0;
%let effective_timestamp_grain = %nrquote(Seconds);
%let purge_grain = %nrquote(1);
%let debug = %nrquote(No);
%let ep_db_create_opts = %nrquote(with serdeproperties %(%'field.delim%'=%'\u0006%', %'line.delim%'=%'\u0007%', %'serialization.format%'=%'\u0006%',%'serialization.escape.crlf%'=%'true%'%) stored as textfile);
%let lcf = lcf.OBJECT;
%let lcf_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="irddev20.vsp.sas.com" AUTHDOMAIN="lcf_dev" 
;
%let lcf_engine = ORACLE;
%let lcf_memtype = DATA;
%let lcf_options = %nrquote();
%let lcf_alter = %nrquote();
%let lcf_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP LCF/OBJECT%(Table%));
%let lcf_type = 1;
%let lcf_label = %nrquote();
%let ep_db_opts_count = %nrquote(1);
%let ep_db_opts = %nrquote(stored as parquet);
%let ep_db_opts1 = %nrquote(stored as parquet);
%let logging = lcf.OBJECT_RUN;
%let logging_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="irddev20.vsp.sas.com" AUTHDOMAIN="lcf_dev" 
;
%let logging_engine = ORACLE;
%let logging_memtype = DATA;
%let logging_options = %nrquote();
%let logging_alter = %nrquote();
%let logging_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP LCF/OBJECT_RUN%(Table%));
%let logging_type = 1;
%let logging_label = %nrquote();
/* Access the data for DIP Hive Staging (hivestg)  */ 
LIBNAME hivestg HADOOP  URI="jdbc:hive2://ird26au.vsp.sas.com:10001/;principal=hive/ird26au.vsp.sas.com@VSP.SAS.COM;ssl=true;sslTrustStore=/sso/sfw/sas/940/hadoopfiles/DigiAndSAS-CA.jks"  HDFS_TEMPDIR="/env/1_dev/landing/" LOGIN_TIMEOUT=0  DEFER=YES  
PORT=10001 SERVER="ird26au.vsp.sas.com"  SCHEMA=dev_staging ;
%rcSet(&syslibrc); 

%let stg_hive_connect =  DEFER=YES URI="jdbc:hive2://ird26au.vsp.sas.com:10001/;principal=hive/ird26au.vsp.sas.com@VSP.SAS.COM;ssl=true;sslTrustStore=/sso/sfw/sas/940/hadoopfiles/DigiAndSAS-CA.jks" HDFS_TEMPDIR="/env/1_dev/landing/" LOGIN_TIMEOUT=0 SERVER="ird26au.vsp.sas.com"  PORT=10001
;
%let stg_hive_engine = HADOOP;
%let stg_hive_path = /IRD/DIP Data Management/1000 Libraries/DIP Hive Staging (hivestg)(Library);
%let stg_hive = hivestg;
/* Access the data for DIP Impala Staging (impstg)  */ 
LIBNAME impstg SASIOIMP  DATABASE=dev_staging  HDFS_TEMPDIR="/env/1_dev/landing/"  DSN=ClouderaImpala64  SCHEMA=dev_staging ;
%rcSet(&syslibrc); 

%let ep_staging_library_connect =  DATABASE=dev_staging DSN=ClouderaImpala64
;
%let ep_staging_library_engine = SASIOIMP;
%let ep_staging_library = impstg;
%let ep_staging_library_path = /IRD/DIP Data Management/1000 Libraries/DIP Impala Staging (impstg)(Library);
%let Source_table_type = %nrquote(view);
%let tagsort = %nrquote(No);

/* List of target columns to keep  */ 
%let _keep = flngdockey fdtmdob fdtmdod fstrwho fdtmwhen record_effective_timestamp 
        record_expiry_timestamp record_active_flag record_deleted_flag 
        insert_object_run_key update_object_run_key;
/* List of target columns to keep  */ 
%let keep = flngdockey fdtmdob fdtmdod fstrwho fdtmwhen record_effective_timestamp 
        record_expiry_timestamp record_active_flag record_deleted_flag 
        insert_object_run_key update_object_run_key;
%change_extract;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end Change Extract **/

%let etls_endTime = %sysfunc(datetime(),datetime.);


