/**************************************************************************** 
 * Job:             tdw_tblnz_customerstd P2H2            A5IKCEC7.BR00004D * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: ird10119au.vsp.sas.com                                  * 
 * Port:            8561                                                    * 
 * Location:        /IRD/DIP Data Management/5000 Processes/10 Raw          * 
 *                   Ingestion                                              * 
 *                                                                          * 
 * Server:          SASApp                                A5IKCEC7.AS000002 * 
 *                                                                          * 
 * Source Table:    TBL_NZ_CUSTOMERSTD -                  A5IKCEC7.BE00003C * 
 *                   edwtdw.TBL_NZ_CUSTOMERSTD                              * 
 * Target Table:    tdw_tbl_nz_customerstd -              A5IKCEC7.BE00006V * 
 *                   impraw.tdw_tbl_nz_customerstd                          * 
 *                                                                          * 
 * Generated on:    Wednesday, October 30, 2019 2:03:59 PM NZDT             * 
 * Generated by:    ird0nxa                                                 * 
 * Version:         SAS Data Integration Studio 4.903                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5IKCEC7.BR00004D);
%let etls_jobName = %nrquote(tdw_tblnz_customerstd P2H2);
%let etls_userID = %nrquote(ird0nxa);

%global applName;
data _null_;
applName="SAS Data Integration Studio";
call symput('applName',%nrstr(applName));
run;
/* Performance Statistics require ARM_PROC sub-system   */ 
%macro etls_startPerformanceStats;
   %log4sas();
   %log4sas_logger(Perf.ARM, 'level=info');
   options armagent=log4sas armsubsys=(ARM_PROC);
   %global _armexec;
   %let _armexec = 1;
   %perfinit(applname="&applName");
   %global etls_recnt;
   %let etls_recnt=-1;
%mend;
%etls_startPerformanceStats;

%macro etls_setArmagent;
   %let armagentLength = %length(%sysfunc(getoption(armagent)));
   %if (&armagentLength eq 0) %then
      %do;
         %log4sas();
         %log4sas_logger(Perf.ARM, 'level=info');
         options armagent=log4sas armsubsys=(ARM_PROC);
      %end;
%mend etls_setArmagent;

%macro etls_setPerfInit;
   %if "&_perfinit" eq "0" %then 
      %do;
         %etls_setArmagent;
         %global _armexec;
         %let _armexec = 1;
         %perfinit(applname="&applName");
      %end;
%mend etls_setPerfInit; 

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(ird10119au.vsp.sas.com);

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Change Extract                        A5IKCEC7.BT0001F2 * 
 * Transform:       Change Extract                                          * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    TBL_NZ_CUSTOMERSTD -                  A5IKCEC7.BE00003C * 
 *                   edwtdw.TBL_NZ_CUSTOMERSTD                              * 
 * Target Table:    tdw_tbl_nz_customerstd -              A5IKCEC7.BE00006V * 
 *                   impraw.tdw_tbl_nz_customerstd                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5IKCEC7.BT0001F2);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for EDW TDW (edwtdw)  */ 
LIBNAME edwtdw ORACLE  DBCOMMIT=0  DBMAX_TEXT=32767  DEFER=YES  PRESERVE_COL_NAMES=YES  PRESERVE_TAB_NAMES=YES  READBUFF=20000  encoding="utf-8" dbclient_max_bytes=2  PATH="DIP_VIP.external"  SCHEMA=TDW  AUTHDOMAIN="edw_prod" ;
%rcSet(&syslibrc); 

/* Access the data for DIP Impala RAW (impraw)  */ 
LIBNAME impraw SASIOIMP  DATABASE=dev_raw  DBMAX_TEXT=32767  DSN=ClouderaImpala64  SCHEMA=dev_raw ;
%rcSet(&syslibrc); 

%let etls_recnt = 0;
%macro etls_recordCheck; 
   %let etls_recCheckExist = %eval(%sysfunc(exist(edwtdw.TBL_NZ_CUSTOMERSTD, DATA)) or 
         %sysfunc(exist(edwtdw.TBL_NZ_CUSTOMERSTD, VIEW))); 
   
   %if (&etls_recCheckExist) %then
   %do;
      proc sql noprint;
         select count(*) into :etls_recnt from edwtdw.TBL_NZ_CUSTOMERSTD;
      quit;
   %end;
%mend etls_recordCheck;
%etls_recordCheck;

%let SYSLAST = %nrquote(edwtdw.TBL_NZ_CUSTOMERSTD); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|GeneratedTransform), metrNam6=_DISROWCNT, metrDef6=Count32)   ;

%let _INPUT_count = 1; 
%let _INPUT = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _INPUT_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="DIP_VIP.external" AUTHDOMAIN="edw_prod" 
;
%let _INPUT_engine = ORACLE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/EDW/EDW TDW/TBL_NZ_CUSTOMERSTD%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _Source = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _Source_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="DIP_VIP.external" AUTHDOMAIN="edw_prod" 
;
%let _Source_engine = ORACLE;
%let _Source_memtype = DATA;
%let _Source_options = %nrquote();
%let _Source_alter = %nrquote();
%let _Source_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/EDW/EDW TDW/TBL_NZ_CUSTOMERSTD%(Table%));
%let _Source_type = 1;
%let _Source_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_connect =  DBMAX_TEXT=32767 DATABASE=dev_raw DSN=ClouderaImpala64
;
%let _OUTPUT_engine = SASIOIMP;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP Impala Raw/tdw_tbl_nz_customerstd%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = flngdockey fstrcustomerclass fstrcustomersegment fstrcustomersubtype 
        fblnspecialtaxresidency fstrcurrenttaxresidency fstrclosurereason 
        fintsmscountrycode fstrsmsareacode fstrsmsphonenumber 
        fdtmincomebalancedate fstrwho effective_from effective_to 
        current_rec_flag fstrcustomersubtypeclass fstrspecialfiletype 
        fstrnonresidenttype record_effective_timestamp record_expiry_timestamp 
        record_active_flag record_deleted_flag insert_object_run_key 
        update_object_run_key;
%let _OUTPUT_col_count = 24;
%let _OUTPUT_col0_name = flngdockey;
%let _OUTPUT_col0_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = 20.;
%let _OUTPUT_col0_informat = 20.;
%let _OUTPUT_col0_label = %nrquote(flngdockey);
%let _OUTPUT_col0_input0 = FLNGDOCKEY;
%let _OUTPUT_col0_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = FLNGDOCKEY;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = fstrcustomerclass;
%let _OUTPUT_col1_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col1_length = 12;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $12.;
%let _OUTPUT_col1_informat = $12.;
%let _OUTPUT_col1_label = %nrquote(fstrcustomerclass);
%let _OUTPUT_col1_input0 = FSTRCUSTOMERCLASS;
%let _OUTPUT_col1_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = FSTRCUSTOMERCLASS;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = fstrcustomersegment;
%let _OUTPUT_col2_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col2_length = 100;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = $100.;
%let _OUTPUT_col2_informat = $100.;
%let _OUTPUT_col2_label = %nrquote(fstrcustomersegment);
%let _OUTPUT_col2_input0 = FSTRCUSTOMERSEGMENT;
%let _OUTPUT_col2_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = FSTRCUSTOMERSEGMENT;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = fstrcustomersubtype;
%let _OUTPUT_col3_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col3_length = 12;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = $12.;
%let _OUTPUT_col3_informat = $12.;
%let _OUTPUT_col3_label = %nrquote(fstrcustomersubtype);
%let _OUTPUT_col3_input0 = FSTRCUSTOMERSUBTYPE;
%let _OUTPUT_col3_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = FSTRCUSTOMERSUBTYPE;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = fblnspecialtaxresidency;
%let _OUTPUT_col4_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 11.;
%let _OUTPUT_col4_informat = 11.;
%let _OUTPUT_col4_label = %nrquote(fblnspecialtaxresidency);
%let _OUTPUT_col4_input0 = FBLNSPECIALTAXRESIDENCY;
%let _OUTPUT_col4_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = FBLNSPECIALTAXRESIDENCY;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = fstrcurrenttaxresidency;
%let _OUTPUT_col5_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col5_length = 100;
%let _OUTPUT_col5_type = $;
%let _OUTPUT_col5_format = $100.;
%let _OUTPUT_col5_informat = $100.;
%let _OUTPUT_col5_label = %nrquote(fstrcurrenttaxresidency);
%let _OUTPUT_col5_input0 = FSTRCURRENTTAXRESIDENCY;
%let _OUTPUT_col5_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = FSTRCURRENTTAXRESIDENCY;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = fstrclosurereason;
%let _OUTPUT_col6_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col6_length = 12;
%let _OUTPUT_col6_type = $;
%let _OUTPUT_col6_format = $12.;
%let _OUTPUT_col6_informat = $12.;
%let _OUTPUT_col6_label = %nrquote(fstrclosurereason);
%let _OUTPUT_col6_input0 = FSTRCLOSUREREASON;
%let _OUTPUT_col6_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = FSTRCLOSUREREASON;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = fintsmscountrycode;
%let _OUTPUT_col7_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col7_length = 8;
%let _OUTPUT_col7_type = ;
%let _OUTPUT_col7_format = 11.;
%let _OUTPUT_col7_informat = 11.;
%let _OUTPUT_col7_label = %nrquote(fintsmscountrycode);
%let _OUTPUT_col7_input0 = FINTSMSCOUNTRYCODE;
%let _OUTPUT_col7_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = FINTSMSCOUNTRYCODE;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = fstrsmsareacode;
%let _OUTPUT_col8_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col8_length = 10;
%let _OUTPUT_col8_type = $;
%let _OUTPUT_col8_format = $10.;
%let _OUTPUT_col8_informat = $10.;
%let _OUTPUT_col8_label = %nrquote(fstrsmsareacode);
%let _OUTPUT_col8_input0 = FSTRSMSAREACODE;
%let _OUTPUT_col8_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input = FSTRSMSAREACODE;
%let _OUTPUT_col8_input_count = 1;
%let _OUTPUT_col9_name = fstrsmsphonenumber;
%let _OUTPUT_col9_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col9_length = 30;
%let _OUTPUT_col9_type = $;
%let _OUTPUT_col9_format = $30.;
%let _OUTPUT_col9_informat = $30.;
%let _OUTPUT_col9_label = %nrquote(fstrsmsphonenumber);
%let _OUTPUT_col9_input0 = FSTRSMSPHONENUMBER;
%let _OUTPUT_col9_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col9_exp = ;
%let _OUTPUT_col9_input = FSTRSMSPHONENUMBER;
%let _OUTPUT_col9_input_count = 1;
%let _OUTPUT_col10_name = fdtmincomebalancedate;
%let _OUTPUT_col10_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col10_length = 8;
%let _OUTPUT_col10_type = ;
%let _OUTPUT_col10_format = DATETIME29.9;
%let _OUTPUT_col10_informat = DATETIME29.9;
%let _OUTPUT_col10_label = %nrquote(fdtmincomebalancedate);
%let _OUTPUT_col10_input0 = FDTMINCOMEBALANCEDATE;
%let _OUTPUT_col10_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col10_exp = ;
%let _OUTPUT_col10_input = FDTMINCOMEBALANCEDATE;
%let _OUTPUT_col10_input_count = 1;
%let _OUTPUT_col11_name = fstrwho;
%let _OUTPUT_col11_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col11_length = 20;
%let _OUTPUT_col11_type = $;
%let _OUTPUT_col11_format = $20.;
%let _OUTPUT_col11_informat = $20.;
%let _OUTPUT_col11_label = %nrquote(fstrwho);
%let _OUTPUT_col11_input0 = FSTRWHO;
%let _OUTPUT_col11_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col11_exp = ;
%let _OUTPUT_col11_input = FSTRWHO;
%let _OUTPUT_col11_input_count = 1;
%let _OUTPUT_col12_name = effective_from;
%let _OUTPUT_col12_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col12_length = 8;
%let _OUTPUT_col12_type = ;
%let _OUTPUT_col12_format = DATETIME29.9;
%let _OUTPUT_col12_informat = DATETIME29.9;
%let _OUTPUT_col12_label = %nrquote(effective_from);
%let _OUTPUT_col12_input0 = EFFECTIVE_FROM;
%let _OUTPUT_col12_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col12_exp = ;
%let _OUTPUT_col12_input = EFFECTIVE_FROM;
%let _OUTPUT_col12_input_count = 1;
%let _OUTPUT_col13_name = effective_to;
%let _OUTPUT_col13_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col13_length = 8;
%let _OUTPUT_col13_type = ;
%let _OUTPUT_col13_format = DATETIME29.9;
%let _OUTPUT_col13_informat = DATETIME29.9;
%let _OUTPUT_col13_label = %nrquote(effective_to);
%let _OUTPUT_col13_input0 = EFFECTIVE_TO;
%let _OUTPUT_col13_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col13_exp = ;
%let _OUTPUT_col13_input = EFFECTIVE_TO;
%let _OUTPUT_col13_input_count = 1;
%let _OUTPUT_col14_name = current_rec_flag;
%let _OUTPUT_col14_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col14_length = 2;
%let _OUTPUT_col14_type = $;
%let _OUTPUT_col14_format = $2.;
%let _OUTPUT_col14_informat = $2.;
%let _OUTPUT_col14_label = %nrquote(current_rec_flag);
%let _OUTPUT_col14_input0 = CURRENT_REC_FLAG;
%let _OUTPUT_col14_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col14_exp = ;
%let _OUTPUT_col14_input = CURRENT_REC_FLAG;
%let _OUTPUT_col14_input_count = 1;
%let _OUTPUT_col15_name = fstrcustomersubtypeclass;
%let _OUTPUT_col15_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col15_length = 12;
%let _OUTPUT_col15_type = $;
%let _OUTPUT_col15_format = $12.;
%let _OUTPUT_col15_informat = $12.;
%let _OUTPUT_col15_label = %nrquote(fstrcustomersubtypeclass);
%let _OUTPUT_col15_input0 = FSTRCUSTOMERSUBTYPECLASS;
%let _OUTPUT_col15_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col15_exp = ;
%let _OUTPUT_col15_input = FSTRCUSTOMERSUBTYPECLASS;
%let _OUTPUT_col15_input_count = 1;
%let _OUTPUT_col16_name = fstrspecialfiletype;
%let _OUTPUT_col16_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col16_length = 12;
%let _OUTPUT_col16_type = $;
%let _OUTPUT_col16_format = $12.;
%let _OUTPUT_col16_informat = $12.;
%let _OUTPUT_col16_label = %nrquote(fstrspecialfiletype);
%let _OUTPUT_col16_input0 = FSTRSPECIALFILETYPE;
%let _OUTPUT_col16_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col16_exp = ;
%let _OUTPUT_col16_input = FSTRSPECIALFILETYPE;
%let _OUTPUT_col16_input_count = 1;
%let _OUTPUT_col17_name = fstrnonresidenttype;
%let _OUTPUT_col17_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col17_length = 100;
%let _OUTPUT_col17_type = $;
%let _OUTPUT_col17_format = $100.;
%let _OUTPUT_col17_informat = $100.;
%let _OUTPUT_col17_label = %nrquote(fstrnonresidenttype);
%let _OUTPUT_col17_input0 = FSTRNONRESIDENTTYPE;
%let _OUTPUT_col17_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _OUTPUT_col17_exp = ;
%let _OUTPUT_col17_input = FSTRNONRESIDENTTYPE;
%let _OUTPUT_col17_input_count = 1;
%let _OUTPUT_col18_name = record_effective_timestamp;
%let _OUTPUT_col18_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col18_length = 8;
%let _OUTPUT_col18_type = ;
%let _OUTPUT_col18_format = DATETIME29.9;
%let _OUTPUT_col18_informat = DATETIME29.9;
%let _OUTPUT_col18_label = %nrquote(record_effective_timestamp);
%let _OUTPUT_col18_exp = ;
%let _OUTPUT_col18_input_count = 0;
%let _OUTPUT_col19_name = record_expiry_timestamp;
%let _OUTPUT_col19_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col19_length = 8;
%let _OUTPUT_col19_type = ;
%let _OUTPUT_col19_format = DATETIME29.9;
%let _OUTPUT_col19_informat = DATETIME29.9;
%let _OUTPUT_col19_label = %nrquote(record_expiry_timestamp);
%let _OUTPUT_col19_exp = ;
%let _OUTPUT_col19_input_count = 0;
%let _OUTPUT_col20_name = record_active_flag;
%let _OUTPUT_col20_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col20_length = 1;
%let _OUTPUT_col20_type = $;
%let _OUTPUT_col20_format = $1.;
%let _OUTPUT_col20_informat = $1.;
%let _OUTPUT_col20_label = %nrquote(record_active_flag);
%let _OUTPUT_col20_exp = ;
%let _OUTPUT_col20_input_count = 0;
%let _OUTPUT_col21_name = record_deleted_flag;
%let _OUTPUT_col21_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col21_length = 1;
%let _OUTPUT_col21_type = $;
%let _OUTPUT_col21_format = $1.;
%let _OUTPUT_col21_informat = $1.;
%let _OUTPUT_col21_label = %nrquote(record_deleted_flag);
%let _OUTPUT_col21_exp = ;
%let _OUTPUT_col21_input_count = 0;
%let _OUTPUT_col22_name = insert_object_run_key;
%let _OUTPUT_col22_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col22_length = 8;
%let _OUTPUT_col22_type = ;
%let _OUTPUT_col22_format = 11.;
%let _OUTPUT_col22_informat = 11.;
%let _OUTPUT_col22_label = %nrquote(insert_object_run_key);
%let _OUTPUT_col22_exp = ;
%let _OUTPUT_col22_input_count = 0;
%let _OUTPUT_col23_name = update_object_run_key;
%let _OUTPUT_col23_table = impraw.tdw_tbl_nz_customerstd;
%let _OUTPUT_col23_length = 8;
%let _OUTPUT_col23_type = ;
%let _OUTPUT_col23_format = 11.;
%let _OUTPUT_col23_informat = 11.;
%let _OUTPUT_col23_label = %nrquote(update_object_run_key);
%let _OUTPUT_col23_exp = ;
%let _OUTPUT_col23_input_count = 0;

%let _target = impraw.tdw_tbl_nz_customerstd;
%let _target_connect =  DBMAX_TEXT=32767 DATABASE=dev_raw DSN=ClouderaImpala64
;
%let _target_engine = SASIOIMP;
%let _target_memtype = DATA;
%let _target_options = %nrquote();
%let _target_alter = %nrquote();
%let _target_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP Impala Raw/tdw_tbl_nz_customerstd%(Table%));
%let _target_type = 1;
%let _target_label = %nrquote();
/* List of target columns to keep  */ 
%let _target_keep = flngdockey fstrcustomerclass fstrcustomersegment fstrcustomersubtype 
        fblnspecialtaxresidency fstrcurrenttaxresidency fstrclosurereason 
        fintsmscountrycode fstrsmsareacode fstrsmsphonenumber 
        fdtmincomebalancedate fstrwho effective_from effective_to 
        current_rec_flag fstrcustomersubtypeclass fstrspecialfiletype 
        fstrnonresidenttype record_effective_timestamp record_expiry_timestamp 
        record_active_flag record_deleted_flag insert_object_run_key 
        update_object_run_key;
%let _target_col_count = 24;
%let _target_col0_name = flngdockey;
%let _target_col0_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col0_length = 8;
%let _target_col0_type = ;
%let _target_col0_format = 20.;
%let _target_col0_informat = 20.;
%let _target_col0_label = %nrquote(flngdockey);
%let _target_col0_input0 = FLNGDOCKEY;
%let _target_col0_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col0_exp = ;
%let _target_col0_input = FLNGDOCKEY;
%let _target_col0_input_count = 1;
%let _target_col1_name = fstrcustomerclass;
%let _target_col1_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col1_length = 12;
%let _target_col1_type = $;
%let _target_col1_format = $12.;
%let _target_col1_informat = $12.;
%let _target_col1_label = %nrquote(fstrcustomerclass);
%let _target_col1_input0 = FSTRCUSTOMERCLASS;
%let _target_col1_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col1_exp = ;
%let _target_col1_input = FSTRCUSTOMERCLASS;
%let _target_col1_input_count = 1;
%let _target_col2_name = fstrcustomersegment;
%let _target_col2_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col2_length = 100;
%let _target_col2_type = $;
%let _target_col2_format = $100.;
%let _target_col2_informat = $100.;
%let _target_col2_label = %nrquote(fstrcustomersegment);
%let _target_col2_input0 = FSTRCUSTOMERSEGMENT;
%let _target_col2_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col2_exp = ;
%let _target_col2_input = FSTRCUSTOMERSEGMENT;
%let _target_col2_input_count = 1;
%let _target_col3_name = fstrcustomersubtype;
%let _target_col3_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col3_length = 12;
%let _target_col3_type = $;
%let _target_col3_format = $12.;
%let _target_col3_informat = $12.;
%let _target_col3_label = %nrquote(fstrcustomersubtype);
%let _target_col3_input0 = FSTRCUSTOMERSUBTYPE;
%let _target_col3_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col3_exp = ;
%let _target_col3_input = FSTRCUSTOMERSUBTYPE;
%let _target_col3_input_count = 1;
%let _target_col4_name = fblnspecialtaxresidency;
%let _target_col4_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col4_length = 8;
%let _target_col4_type = ;
%let _target_col4_format = 11.;
%let _target_col4_informat = 11.;
%let _target_col4_label = %nrquote(fblnspecialtaxresidency);
%let _target_col4_input0 = FBLNSPECIALTAXRESIDENCY;
%let _target_col4_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col4_exp = ;
%let _target_col4_input = FBLNSPECIALTAXRESIDENCY;
%let _target_col4_input_count = 1;
%let _target_col5_name = fstrcurrenttaxresidency;
%let _target_col5_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col5_length = 100;
%let _target_col5_type = $;
%let _target_col5_format = $100.;
%let _target_col5_informat = $100.;
%let _target_col5_label = %nrquote(fstrcurrenttaxresidency);
%let _target_col5_input0 = FSTRCURRENTTAXRESIDENCY;
%let _target_col5_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col5_exp = ;
%let _target_col5_input = FSTRCURRENTTAXRESIDENCY;
%let _target_col5_input_count = 1;
%let _target_col6_name = fstrclosurereason;
%let _target_col6_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col6_length = 12;
%let _target_col6_type = $;
%let _target_col6_format = $12.;
%let _target_col6_informat = $12.;
%let _target_col6_label = %nrquote(fstrclosurereason);
%let _target_col6_input0 = FSTRCLOSUREREASON;
%let _target_col6_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col6_exp = ;
%let _target_col6_input = FSTRCLOSUREREASON;
%let _target_col6_input_count = 1;
%let _target_col7_name = fintsmscountrycode;
%let _target_col7_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col7_length = 8;
%let _target_col7_type = ;
%let _target_col7_format = 11.;
%let _target_col7_informat = 11.;
%let _target_col7_label = %nrquote(fintsmscountrycode);
%let _target_col7_input0 = FINTSMSCOUNTRYCODE;
%let _target_col7_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col7_exp = ;
%let _target_col7_input = FINTSMSCOUNTRYCODE;
%let _target_col7_input_count = 1;
%let _target_col8_name = fstrsmsareacode;
%let _target_col8_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col8_length = 10;
%let _target_col8_type = $;
%let _target_col8_format = $10.;
%let _target_col8_informat = $10.;
%let _target_col8_label = %nrquote(fstrsmsareacode);
%let _target_col8_input0 = FSTRSMSAREACODE;
%let _target_col8_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col8_exp = ;
%let _target_col8_input = FSTRSMSAREACODE;
%let _target_col8_input_count = 1;
%let _target_col9_name = fstrsmsphonenumber;
%let _target_col9_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col9_length = 30;
%let _target_col9_type = $;
%let _target_col9_format = $30.;
%let _target_col9_informat = $30.;
%let _target_col9_label = %nrquote(fstrsmsphonenumber);
%let _target_col9_input0 = FSTRSMSPHONENUMBER;
%let _target_col9_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col9_exp = ;
%let _target_col9_input = FSTRSMSPHONENUMBER;
%let _target_col9_input_count = 1;
%let _target_col10_name = fdtmincomebalancedate;
%let _target_col10_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col10_length = 8;
%let _target_col10_type = ;
%let _target_col10_format = DATETIME29.9;
%let _target_col10_informat = DATETIME29.9;
%let _target_col10_label = %nrquote(fdtmincomebalancedate);
%let _target_col10_input0 = FDTMINCOMEBALANCEDATE;
%let _target_col10_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col10_exp = ;
%let _target_col10_input = FDTMINCOMEBALANCEDATE;
%let _target_col10_input_count = 1;
%let _target_col11_name = fstrwho;
%let _target_col11_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col11_length = 20;
%let _target_col11_type = $;
%let _target_col11_format = $20.;
%let _target_col11_informat = $20.;
%let _target_col11_label = %nrquote(fstrwho);
%let _target_col11_input0 = FSTRWHO;
%let _target_col11_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col11_exp = ;
%let _target_col11_input = FSTRWHO;
%let _target_col11_input_count = 1;
%let _target_col12_name = effective_from;
%let _target_col12_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col12_length = 8;
%let _target_col12_type = ;
%let _target_col12_format = DATETIME29.9;
%let _target_col12_informat = DATETIME29.9;
%let _target_col12_label = %nrquote(effective_from);
%let _target_col12_input0 = EFFECTIVE_FROM;
%let _target_col12_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col12_exp = ;
%let _target_col12_input = EFFECTIVE_FROM;
%let _target_col12_input_count = 1;
%let _target_col13_name = effective_to;
%let _target_col13_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col13_length = 8;
%let _target_col13_type = ;
%let _target_col13_format = DATETIME29.9;
%let _target_col13_informat = DATETIME29.9;
%let _target_col13_label = %nrquote(effective_to);
%let _target_col13_input0 = EFFECTIVE_TO;
%let _target_col13_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col13_exp = ;
%let _target_col13_input = EFFECTIVE_TO;
%let _target_col13_input_count = 1;
%let _target_col14_name = current_rec_flag;
%let _target_col14_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col14_length = 2;
%let _target_col14_type = $;
%let _target_col14_format = $2.;
%let _target_col14_informat = $2.;
%let _target_col14_label = %nrquote(current_rec_flag);
%let _target_col14_input0 = CURRENT_REC_FLAG;
%let _target_col14_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col14_exp = ;
%let _target_col14_input = CURRENT_REC_FLAG;
%let _target_col14_input_count = 1;
%let _target_col15_name = fstrcustomersubtypeclass;
%let _target_col15_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col15_length = 12;
%let _target_col15_type = $;
%let _target_col15_format = $12.;
%let _target_col15_informat = $12.;
%let _target_col15_label = %nrquote(fstrcustomersubtypeclass);
%let _target_col15_input0 = FSTRCUSTOMERSUBTYPECLASS;
%let _target_col15_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col15_exp = ;
%let _target_col15_input = FSTRCUSTOMERSUBTYPECLASS;
%let _target_col15_input_count = 1;
%let _target_col16_name = fstrspecialfiletype;
%let _target_col16_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col16_length = 12;
%let _target_col16_type = $;
%let _target_col16_format = $12.;
%let _target_col16_informat = $12.;
%let _target_col16_label = %nrquote(fstrspecialfiletype);
%let _target_col16_input0 = FSTRSPECIALFILETYPE;
%let _target_col16_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col16_exp = ;
%let _target_col16_input = FSTRSPECIALFILETYPE;
%let _target_col16_input_count = 1;
%let _target_col17_name = fstrnonresidenttype;
%let _target_col17_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col17_length = 100;
%let _target_col17_type = $;
%let _target_col17_format = $100.;
%let _target_col17_informat = $100.;
%let _target_col17_label = %nrquote(fstrnonresidenttype);
%let _target_col17_input0 = FSTRNONRESIDENTTYPE;
%let _target_col17_input0_table = edwtdw.TBL_NZ_CUSTOMERSTD;
%let _target_col17_exp = ;
%let _target_col17_input = FSTRNONRESIDENTTYPE;
%let _target_col17_input_count = 1;
%let _target_col18_name = record_effective_timestamp;
%let _target_col18_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col18_length = 8;
%let _target_col18_type = ;
%let _target_col18_format = DATETIME29.9;
%let _target_col18_informat = DATETIME29.9;
%let _target_col18_label = %nrquote(record_effective_timestamp);
%let _target_col18_exp = ;
%let _target_col18_input_count = 0;
%let _target_col19_name = record_expiry_timestamp;
%let _target_col19_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col19_length = 8;
%let _target_col19_type = ;
%let _target_col19_format = DATETIME29.9;
%let _target_col19_informat = DATETIME29.9;
%let _target_col19_label = %nrquote(record_expiry_timestamp);
%let _target_col19_exp = ;
%let _target_col19_input_count = 0;
%let _target_col20_name = record_active_flag;
%let _target_col20_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col20_length = 1;
%let _target_col20_type = $;
%let _target_col20_format = $1.;
%let _target_col20_informat = $1.;
%let _target_col20_label = %nrquote(record_active_flag);
%let _target_col20_exp = ;
%let _target_col20_input_count = 0;
%let _target_col21_name = record_deleted_flag;
%let _target_col21_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col21_length = 1;
%let _target_col21_type = $;
%let _target_col21_format = $1.;
%let _target_col21_informat = $1.;
%let _target_col21_label = %nrquote(record_deleted_flag);
%let _target_col21_exp = ;
%let _target_col21_input_count = 0;
%let _target_col22_name = insert_object_run_key;
%let _target_col22_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col22_length = 8;
%let _target_col22_type = ;
%let _target_col22_format = 11.;
%let _target_col22_informat = 11.;
%let _target_col22_label = %nrquote(insert_object_run_key);
%let _target_col22_exp = ;
%let _target_col22_input_count = 0;
%let _target_col23_name = update_object_run_key;
%let _target_col23_table = impraw.tdw_tbl_nz_customerstd;
%let _target_col23_length = 8;
%let _target_col23_type = ;
%let _target_col23_format = 11.;
%let _target_col23_informat = 11.;
%let _target_col23_label = %nrquote(update_object_run_key);
%let _target_col23_exp = ;
%let _target_col23_input_count = 0;


%let ep_key_cols = flngdockey;
%let ep_key_cols_count = 1;
%let ep_key_cols0 = 1;
%let ep_key_cols1 = flngdockey;
%let where = ;
%let change_capture_timestamp = EFFECTIVE_FROM;
%let change_capture_timestamp_count = 1;
%let change_capture_timestamp0 = 1;
%let change_capture_timestamp1 = EFFECTIVE_FROM;
%let history_type = %nrquote(H2);
%let duplication_grain = %nrquote(1);
%let h2_effective_column = EFFECTIVE_TO;
%let h2_effective_column_count = 1;
%let h2_effective_column0 = 1;
%let h2_effective_column1 = EFFECTIVE_TO;
%let effective_column = effective_from;
%let effective_column_count = 1;
%let effective_column0 = 1;
%let effective_column1 = effective_from;
%let to_timestamp = ;
%let to_timestamp_count = 0;
%let to_timestamp0 = 0;
%let effective_timestamp_grain = %nrquote(Seconds);
%let purge_grain = %nrquote(1);
%let debug = %nrquote(No);
%let ep_db_create_opts = %nrquote(with serdeproperties %(%'field.delim%'=%'\u0006%', %'line.delim%'=%'\u0007%', %'serialization.format%'=%'\u0006%',%'serialization.escape.crlf%'=%'true%'%) stored as textfile);
%let lcf = lcf.OBJECT;
%let lcf_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="irddev20.vsp.sas.com" AUTHDOMAIN="lcf_dev" 
;
%let lcf_engine = ORACLE;
%let lcf_memtype = DATA;
%let lcf_options = %nrquote();
%let lcf_alter = %nrquote();
%let lcf_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP LCF/OBJECT%(Table%));
%let lcf_type = 1;
%let lcf_label = %nrquote();
%let ep_db_opts_count = %nrquote(1);
%let ep_db_opts = %nrquote(stored as parquet);
%let ep_db_opts1 = %nrquote(stored as parquet);
%let logging = lcf.OBJECT_RUN;
%let logging_connect =  DBMAX_TEXT=32767 DEFER=YES encoding="utf-8" READBUFF=20000 dbclient_max_bytes=2 PATH="irddev20.vsp.sas.com" AUTHDOMAIN="lcf_dev" 
;
%let logging_engine = ORACLE;
%let logging_memtype = DATA;
%let logging_options = %nrquote();
%let logging_alter = %nrquote();
%let logging_path = %nrquote(/IRD/DIP Data Management/3000 Repositories/DIP/DIP LCF/OBJECT_RUN%(Table%));
%let logging_type = 1;
%let logging_label = %nrquote();
/* Access the data for DIP Hive Staging (hivestg)  */ 
LIBNAME hivestg HADOOP  URI="jdbc:hive2://ird26au.vsp.sas.com:10001/;principal=hive/ird26au.vsp.sas.com@VSP.SAS.COM;ssl=true;sslTrustStore=/sso/sfw/sas/940/hadoopfiles/DigiAndSAS-CA.jks"  HDFS_TEMPDIR="/env/1_dev/landing/" LOGIN_TIMEOUT=0  DEFER=YES  
PORT=10001 SERVER="ird26au.vsp.sas.com"  SCHEMA=dev_staging ;
%rcSet(&syslibrc); 

%let stg_hive_connect =  DEFER=YES URI="jdbc:hive2://ird26au.vsp.sas.com:10001/;principal=hive/ird26au.vsp.sas.com@VSP.SAS.COM;ssl=true;sslTrustStore=/sso/sfw/sas/940/hadoopfiles/DigiAndSAS-CA.jks" HDFS_TEMPDIR="/env/1_dev/landing/" LOGIN_TIMEOUT=0 SERVER="ird26au.vsp.sas.com"  PORT=10001
;
%let stg_hive_engine = HADOOP;
%let stg_hive_path = /IRD/DIP Data Management/1000 Libraries/DIP Hive Staging (hivestg)(Library);
%let stg_hive = hivestg;
/* Access the data for DIP Impala Staging (impstg)  */ 
LIBNAME impstg SASIOIMP  DATABASE=dev_staging  HDFS_TEMPDIR="/env/1_dev/landing/"  DSN=ClouderaImpala64  SCHEMA=dev_staging ;
%rcSet(&syslibrc); 

%let ep_staging_library_connect =  DATABASE=dev_staging DSN=ClouderaImpala64
;
%let ep_staging_library_engine = SASIOIMP;
%let ep_staging_library = impstg;
%let ep_staging_library_path = /IRD/DIP Data Management/1000 Libraries/DIP Impala Staging (impstg)(Library);
%let Source_table_type = %nrquote(view);
%let tagsort = %nrquote(No);

/* List of target columns to keep  */ 
%let _keep = flngdockey fstrcustomerclass fstrcustomersegment fstrcustomersubtype 
        fblnspecialtaxresidency fstrcurrenttaxresidency fstrclosurereason 
        fintsmscountrycode fstrsmsareacode fstrsmsphonenumber 
        fdtmincomebalancedate fstrwho effective_from effective_to 
        current_rec_flag fstrcustomersubtypeclass fstrspecialfiletype 
        fstrnonresidenttype record_effective_timestamp record_expiry_timestamp 
        record_active_flag record_deleted_flag insert_object_run_key 
        update_object_run_key;
/* List of target columns to keep  */ 
%let keep = flngdockey fstrcustomerclass fstrcustomersegment fstrcustomersubtype 
        fblnspecialtaxresidency fstrcurrenttaxresidency fstrclosurereason 
        fintsmscountrycode fstrsmsareacode fstrsmsphonenumber 
        fdtmincomebalancedate fstrwho effective_from effective_to 
        current_rec_flag fstrcustomersubtypeclass fstrspecialfiletype 
        fstrnonresidenttype record_effective_timestamp record_expiry_timestamp 
        record_active_flag record_deleted_flag insert_object_run_key 
        update_object_run_key;
%change_extract;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%perfstop(metrVal6=%sysfunc(max(&etls_recnt,-1)));
%let etls_recnt=-1;



/** Step end Change Extract **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/* Turn off performance statistics collection  */ 
data _null_;
   if "&_perfinit" eq "1" then 
      call execute('%perfend;');
      
run;

