 /********************************************************
25/11/19 ird0sxd initial script for minor enhacements to LCF.

********************************************************/

ALTER TABLE OBJECT_RUN ADD TASK8 VARCHAR2(50);
ALTER TABLE OBJECT_RUN ADD TASK9 VARCHAR2(50);
ALTER TABLE OBJECT_RUN ADD TASK10 VARCHAR2(50);

ALTER TABLE OBJECT_RUN ADD TASK8_START_TIME TIMESTAMP(6);
ALTER TABLE OBJECT_RUN ADD TASK9_START_TIME TIMESTAMP(6);
ALTER TABLE OBJECT_RUN ADD TASK10_START_TIME TIMESTAMP(6);



ALTER TABLE OBJECT_RUN ADD TASK8_END_TIME TIMESTAMP(6);
ALTER TABLE OBJECT_RUN ADD TASK9_END_TIME TIMESTAMP(6);
ALTER TABLE OBJECT_RUN ADD TASK10_END_TIME TIMESTAMP(6);


ALTER TABLE OBJECT ADD CAS_UPLOAD VARCHAR2(1) DEFAULT 'N' ;
ALTER TABLE OBJECT ADD  BATCH_NAME VARCHAR2(15);

UPDATE OBJECT SET CAS_UPLOAD='N' WHERE SOURCE_OBJECT_NAME NOT IN ('TBLACCOUNT','TBLACCOUNTINFO','TBLCUSTOMERINFO','TBLCUSTOMERMAIL','TBLDOCPOSTTRANSACTION','TBLINDICATOR','TBLMAILITEM','TBLNZ_CUSTOMERSTD','TBLWEBNOTICE');
UPDATE OBJECT SET CAS_UPLOAD='Y' WHERE SOURCE_OBJECT_NAME IN ('TBLACCOUNT','TBLACCOUNTINFO','TBLCUSTOMERINFO','TBLCUSTOMERMAIL','TBLDOCPOSTTRANSACTION','TBLINDICATOR','TBLMAILITEM','TBLNZ_CUSTOMERSTD','TBLWEBNOTICE');

SELECT * FROM OBJECT WHERE CAS_UPLOAD='Y' ;
COMMIT;


SELECT * FROM DIP_CONFIG;
SET DEFINE OFF;
TRUNCATE TABLE DIP_CONFIG;
INSERT INTO DIP_CONFIG VALUES ('DIP_ETL_EMAIL','Michael.Danusantoso@ird.govt.nz');
--Insert into DIP_CONFIG (KEY,VALUE) values ('DIP_ETL_EMAIL','dipetldev@ird.govt.nz');
Insert into DIP_CONFIG (KEY,VALUE) values ('DASHBOARD_URL','https://discovery.dip-lab.ird.govt.nz/SASReportViewer/?reportUri=%2Freports%2Freports%2F130079d1-9498-400e-ab89-0ba9dfd04ab3&page=vi6');
Insert into DIP_CONFIG (KEY,VALUE) values ('START_CUTOFF_DATE_R3','2019-04-21');
Insert into DIP_CONFIG (KEY,VALUE) values ('START_CUTOFF_DATE_R1','2017-02-05');
Insert into DIP_CONFIG (KEY,VALUE) values ('START_CUTOFF_DATE_R2','2018-04-18');
Insert into DIP_CONFIG (KEY,VALUE) values ('DAYS_TO_BACKFILL','0');
COMMIT;