insert into  OBJECT_RUNNING_IN_THIS_ENV 
select 'APP_TBLAUDITGROUPTOAUDIT' from dual
union all select 'APP_TBLBALANCE' from dual
union all select 'APP_TBLBANKACCOUNTPAYMENT' from dual
union all select 'APP_TBLCLTPMNTPLANBILLITM' from dual
union all select 'APP_TBLCOLLECTPAYMNTPLANSHDL' from dual
union all select 'APP_TBLGARNISHTOGARNISHEE' from dual
union all select 'APP_TBLNZ_ACCKSFINFO' from dual
union all select 'APP_TBLNZ_ACCKSSINFO' from dual
union all select 'APP_TBLNZ_ACCSLS' from dual
union all select 'APP_TBLNZ_ACCSLSHISTORY' from dual
union all select 'APP_TBLNZ_CASSLSRECALL' from dual
union all select 'APP_TBLNZ_GARNISHTOPBI' from dual
union all select 'APP_TBLNZ_INCRRCTDEDCASEDTL' from dual
union all select 'APP_TBLNZ_KSEMPLOYRCHSNSCHMS' from dual
union all select 'APP_TBLNZ_KSFDEFAULTSCHEME' from dual
union all select 'APP_TBLNZ_KSSCONTRIBUTION' from dual
union all select 'APP_TBLNZ_KSSCONTRIBUTNBLN' from dual
union all select 'APP_TBLNZ_KSSCONTRDETAIL' from dual
union all select 'APP_TBLNZ_KSSDEFAULTSCHMALLOC' from dual
union all select 'APP_TBLNZ_KSSLINEITEM' from dual
union all select 'APP_TBLNZ_KSSMEMBERTOSCHEME' from dual
union all select 'APP_TBLNZ_KSSPRORATAINTEREST' from dual
union all select 'APP_TBLNZ_KSSRESIDUAL' from dual
union all select 'APP_TBLNZ_KSSWITHDRAWAL' from dual
union all select 'APP_TBLNZ_LINKMAILREDIRECT' from dual
union all select 'APP_TBLNZ_RTNSLSOBLIGATNS2013' from dual
union all select 'APP_TBLNZ_RTNSLSOBLNZB' from dual
union all select 'APP_TBLNZ_RTNSLSOBLOBB' from dual
union all select 'APP_TBLNZ_SLSBORROWERTYPE' from dual
union all select 'APP_TBLNZ_SLSCUSTOMSMOVEMENT' from dual
union all select 'APP_TBLNZ_SLSUNLINKEDDEDUCT' from dual
union all select 'APP_TBLNZ_SLSWORLDWIDEINCOME' from dual
union all select 'APP_TBLNZ_STUDYLINKMAINTAINLG' from dual
union all select 'APP_TBLNZ_STUDYLINKOUT' from dual
union all select 'APP_TBLNZ_STUDYLNKVALLOG' from dual
union all select 'APP_TBLNZ_TRSTOBORROWERTYPE' from dual
union all select 'APP_TBLRFNREFUND' from dual
union all select 'APP_TBLRFNREFUNDTRANSACTION' from dual
union all select 'REF_LANINDICATORLEVEL' from dual
union all select 'REF_LANINDICATORREASON' from dual
union all select 'REF_LANNZ_KSSCONTRDETAILTYPE' from dual
union all select 'REF_LANNZ_KSSCONTRIBUTIONTYPE' from dual
union all select 'REF_LANNZ_KSSCONTRIBRVRSRSN' from dual
union all select 'REF_LANNZ_KSSCONTRSTATUS' from dual
union all select 'REF_LANNZ_KSSFINHARDSHIPRSN' from dual
union all select 'REF_LANNZ_KSSMBRCEASEREASON' from dual
union all select 'REF_LANNZ_KSSSCHEMECHOICETYPE' from dual
union all select 'REF_LANNZ_KSSWITHDRAWALREASON' from dual
union all select 'REF_LANNZ_SLSBORROWERTYPE' from dual
