insert into object_running_in_this_env 
select 'WRQ_TBLWEBSESSION' from dual
union all select 'WRQ_TBLNZ_LINKPCGTOPARTNER' from dual
union all select 'REF_LANREASONRTNADJ' from dual
union all select 'REF_LANNZ_PROVISIONALTAXMTHD' from dual
union all select 'REF_LANNZ_CLIENTLISTACCESSLVL' from dual
union all select 'REF_LANNZ_AMENDREASON' from dual
union all select 'REF_LANIDTYPE' from dual
union all select 'APP_TBLTRANSOFFSETDETAIL' from dual
union all select 'APP_TBLRECOVERYAMOUNT' from dual
union all select 'APP_TBLRECOVERY' from dual
union all select 'APP_TBLNZ_TAILOREDTAX' from dual
union all select 'APP_TBLNZ_STUDYLINKCEASELOG' from dual
union all select 'APP_TBLNZ_STDYLNKENRLMAINTLOG' from dual
union all select 'APP_TBLNZ_RTNSLSOBLIGATIONS' from dual
union all select 'APP_TBLNZ_RTNNITPRTATTRL' from dual
union all select 'APP_TBLNZ_RTNIITCOEXISTENCE' from dual
union all select 'APP_TBLNZ_RELPRTNRPRD' from dual
union all select 'APP_TBLNZ_RELNSHIPCHILDPRD' from dual
union all select 'APP_TBLNZ_RELATIONSHPROLERVRS' from dual
union all select 'APP_TBLNZ_RATXNDEBTRAGNGDTL' from dual
union all select 'APP_TBLNZ_RATXNDEBTORAGINGPRD' from dual
union all select 'APP_TBLNZ_PAYMENTADDTNLINF' from dual
union all select 'APP_TBLNZ_LNKKSFADM' from dual
union all select 'APP_TBLNZ_KSSPRORATAPOSTING' from dual
union all select 'APP_TBLNZ_KSSHOLDTILLDATE' from dual
union all select 'APP_TBLNZ_INGJOINTLYLIABLE' from dual
union all select 'APP_TBLNZ_INDTAXPREPPROFILE' from dual
union all select 'APP_TBLNZ_FAMPROTECTEDFTC' from dual
union all select 'APP_TBLNZ_FAMMSDADMINISTRATN' from dual
union all select 'APP_TBLNZ_FAMMFTC' from dual
union all select 'APP_TBLNZ_FAMLINKMODIFICATION' from dual
union all select 'APP_TBLNZ_FAMIWTC' from dual
union all select 'APP_TBLNZ_FAMEVENTLOG' from dual
union all select 'APP_TBLNZ_FAMCHILDSUPPORTACT' from dual
union all select 'APP_TBLNZ_FAMCHANGELOG' from dual
union all select 'APP_TBLNZ_DEDUCTIONLTRQUE' from dual
union all select 'APP_TBLNZ_CUSTOMSPOI' from dual
union all select 'APP_TBLNZ_CUSTOMSALS' from dual
union all select 'APP_TBLNZ_CSTINDINFO' from dual
union all select 'APP_TBLNZ_CASECOLNEGOTIATION' from dual
union all select 'APP_TBLNZ_CAMPAIGNTREATMENTS' from dual
union all select 'APP_TBLNZ_BILLITEMTOSTATEMENT' from dual
union all select 'APP_TBLNZ_ACCOUNTDATEHISTORY' from dual
union all select 'APP_TBLNZ_ACCPPL' from dual
union all select 'APP_TBLNZ_ACCKIWISAVERMBRINFO' from dual
union all select 'APP_TBLNZ_ACCGMD' from dual
union all select 'APP_TBLNZ_ACCAILSECURITIES' from dual
union all select 'APP_TBLGARNISHTODEBTSOURCE' from dual
union all select 'APP_TBLDOCTRN' from dual
union all select 'APP_TBLCOLLECTSTAGETOSTAGE' from dual
union all select 'APP_TBLCOLLECTDETAIL' from dual
union all select 'APP_TBLAUDITPERIOD' from dual
union all select 'DSS_INSTALMENT_SRC_PLANS_SUM' from dual
union all select 'DSS_RETURNS_KEYPOINTS_IR9' from dual
union all select 'DSS_INSTALMENT_AGMT_ELEMENTS' from dual
union all select 'DSS_EDW_VOICE_AGENT' from dual