/*        
07/11/19 ird0sxd initial version

*/
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (13,'MRT','ORACLE','DATAMART','EDWMRT');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (113,'CME','ORACLE','CMEOWN','EDWCME');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (114,'EFP','ORACLE','EFTPOS','ALCEFP');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (115,'XT5','ORACLE','KXT5','EDWXT5');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (1,'DSS','ORACLE','DSS','EDWDSS');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (2,'LCF','ORACLE','LCF','LCF');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (3,'TDW','ORACLE','TDW','EDWTDW');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (4,'SREF','MSSQL','NZO_GTREF','STRREF');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (92,'SSTC','MSSQL','NZO_GTSTC','STRSTC');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (8,'SAPP','MSSQL','NZO_GTAPP','STRAPP');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (9,'SWRQ','MSSQL','NZO_GTWRQ','STRWRQ');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (10,'PAPP','MSSQL','NZP_GTAPP','PAPP');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (11,'PWRQ','MSSQL','NZP_GTWRQ','PWRQ');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (12,'SFRD','MSSQL','NZO_GTFRD','STRFRD');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (52,'PTY','ORACLE','PROPERTY','ALCPTY');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (53,'CMP','ORACLE','COMPANIES','ALCCMP');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (54,'DTH','ORACLE','DIA_DEATHS','ALCDTH');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (72,'SMY','ORACLE','SUMMARY','EDWSMY');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (32,'HHO','ORACLE','17THHO','EDWHHO');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (36,'WCH','ORACLE','67AWCH','EDWWCH');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (37,'OWN','ORACLE','BESSOWN','EDWOWN');
Insert into SYSTEM_SCHEMA (SYSTEM_SCHEMA_KEY,SYSTEM_NAME,SYSTEM_TYPE,SCHEMA_NAME,SAS_LIB_REF) values (38,'XT4','ORACLE','SXT4','EDWXT4');
commit;