SELECT * FROM system_schema;



insert into system_Schema (SYSTEM_SCHEMA_KEY,SYSTEM_NAME, SYSTEM_TYPE, SCHEMA_NAME, SAS_LIB_REF,SCHEMA_PREFIX) values (SEQ_SYSTEM_SCHEMA_KEY.nextval,'SAPP','MSSQL','NZS_GTAPP','STRAPP','APP');
insert into system_Schema (SYSTEM_SCHEMA_KEY,SYSTEM_NAME, SYSTEM_TYPE, SCHEMA_NAME, SAS_LIB_REF,SCHEMA_PREFIX) values (SEQ_SYSTEM_SCHEMA_KEY.nextval,'SREF','MSSQL','NZS_GTREF','STRREF','REF');

COMMIT;

SELECT * FROM SYSTEM_SCHEMA;