-- ird0sxd 24022020 Script to load non raw tables to OBJECT tables
--         25022020 Update script to correct INDIVIDUAL_DIM table name
-- ird0sxd 25022020 Setup TARGET_DB to null, LOAD_PATTERN_NAME to NULL for refined objects. 

-- -- if this constraint exists drop it
ALTER TABLE OBJECT
DROP CONSTRAINT ING_MODE_CK ;


-- if this constraint exists drop it
ALTER TABLE OBJECT
DROP CONSTRAINT ING_MODE; 

ALTER TABLE OBJECT 
ADD CONSTRAINT ING_MODE_CK CHECK (INGESTION_MODE IN ('JNL', 'ALL', 'ING','NA'));



-- Find out the system schema key for the refined layer. This would be different betwee dev, test, prod.

SELECT   SYSTEM_SCHEMA_KEY,sas_lib_ref
FROM SYSTEM_SCHEMA
WHERE SCHEMA_NAME='REFINED' ;


-- For each of these statements paass the SYSTEM_SCHEMA_KEY we got from running the above query.
-- Also pass your irdxxxx userid as the user id.

INSERT INTO LCF.OBJECT (SYSTEM_SCHEMA_KEY, TARGET_OBJECT_NAME,  TARGET_DB, SOURCE_OBJECT_TYPE, SAS_LIB_REF,  LAYER, CAS_UPLOAD,INGESTION_MODE, LOAD_PATTERN_NAME, CREATED_DATE, CREATED_BY) 
VALUES (&system_schema_key, 'ORGANISATION_DIM', null, 'TABLE', 'IMPRFN','REFINED','Y','NA',NULL, SYSDATE,'&USERID');

INSERT INTO LCF.OBJECT (SYSTEM_SCHEMA_KEY, TARGET_OBJECT_NAME,  TARGET_DB, SOURCE_OBJECT_TYPE, SAS_LIB_REF,  LAYER, CAS_UPLOAD,INGESTION_MODE, LOAD_PATTERN_NAME, CREATED_DATE, CREATED_BY) 
VALUES (&system_schema_key, 'PARTY_DIM', null, 'TABLE', 'IMPRFN','REFINED','Y','NA',NULL, SYSDATE,'&USERID');

INSERT INTO LCF.OBJECT (SYSTEM_SCHEMA_KEY, TARGET_OBJECT_NAME,  TARGET_DB, SOURCE_OBJECT_TYPE, SAS_LIB_REF,  LAYER,CAS_UPLOAD,INGESTION_MODE, LOAD_PATTERN_NAME, CREATED_DATE, CREATED_BY) 
VALUES (&system_schema_key, 'INDIVIDUAL_DIM',null, 'TABLE', 'IMPRFN','REFINED','Y','NA',NULL,SYSDATE,'&USERID');


SELECT OBJECT_KEY, SYSTEM_sCHEMA_KEY, TARGET_OBJECT_NAME, OBJECT_SHORT_NAME,SOURCE_OBJECT_TYPE, SAS_LIB_REF, CAS_UPLOAD,LAYER,INGESTION_MODE 
FROM OBJECT WHERE TARGET_OBJECT_NAME LIKE '%DIM%';

COMMIT;

