CREATE TABLE lab_fcp_raw.ptn_coy_raw_company_document (
  co_id VARCHAR(100),
  co_name VARCHAR(2000),
  co_nzbn VARCHAR(2000),
  doc_id BIGINT,
  doc_type_desc VARCHAR(2000),
  doc_type_code VARCHAR(2000),
  doc_barcode VARCHAR(2000),
  doc_submitted_date TIMESTAMP,
  doc_status_desc VARCHAR(100),
  doc_status_changed_date TIMESTAMP,
  doc_private_yn VARCHAR(2),
  doc_archived_yn VARCHAR(2),
  doc_presenter_org_id BIGINT,
  doc_presenter_medsec_id VARCHAR(2000),
  doc_presenter_name VARCHAR(2000),
  doc_presenter_address_1 VARCHAR(2000),
  doc_presenter_address_2 VARCHAR(2000),
  doc_presenter_address_3 VARCHAR(2000),
  doc_presenter_address_4 VARCHAR(2000),
  doc_presenter_post_code VARCHAR(100),
  doc_presenter_phone_no VARCHAR(2000),
  doc_presenter_mobile_no VARCHAR(2000),
  doc_presenter_fax_no VARCHAR(2000),
  doc_presenter_ip_address VARCHAR(2000),
  doc_presenter_email_address VARCHAR(2000),
  doc_presenter_country_name VARCHAR(2000),
  doc_ffs_id BIGINT,
  doc_fra_year_no INT,
  doc_fra_month_no INT,
  doc_ffs_status_desc VARCHAR(60),
  doc_ffs_last_changed_date TIMESTAMP,
  doc_size_bytes BIGINT,
  doc_size_desc VARCHAR(40),
  ir_logical_delete_ind VARCHAR(2),
  ir_logical_delete_source VARCHAR(16),
  ir_valid_from TIMESTAMP,
  ir_valid_to TIMESTAMP,
  ir_dup_count BIGINT
)
partitioned by (ir_source varchar(16))
STORED AS PARQUET;

insert into lab_fcp_raw.ptn_coy_raw_company_document 
(
co_id,
co_name,
co_nzbn,
doc_id,
doc_type_desc,
doc_type_code,
doc_barcode,
doc_submitted_date,
doc_status_desc,
doc_status_changed_date,
doc_private_yn,
doc_archived_yn,
doc_presenter_org_id,
doc_presenter_medsec_id,
doc_presenter_name,
doc_presenter_address_1,
doc_presenter_address_2,
doc_presenter_address_3,
doc_presenter_address_4,
doc_presenter_post_code,
doc_presenter_phone_no,
doc_presenter_mobile_no,
doc_presenter_fax_no,
doc_presenter_ip_address,
doc_presenter_email_address,
doc_presenter_country_name,
doc_ffs_id,
doc_fra_year_no,
doc_fra_month_no,
doc_ffs_status_desc,
doc_ffs_last_changed_date,
doc_size_bytes,
doc_size_desc,
ir_source,
ir_logical_delete_ind,
ir_logical_delete_source,
ir_valid_from,
ir_valid_to,
ir_dup_count
)
select  
co_id,
co_name,
co_nzbn,
doc_id,
doc_type_desc,
doc_type_code,
doc_barcode,
doc_submitted_date,
doc_status_desc,
doc_status_changed_date,
doc_private_yn,
doc_archived_yn,
doc_presenter_org_id,
doc_presenter_medsec_id,
doc_presenter_name,
doc_presenter_address_1,
doc_presenter_address_2,
doc_presenter_address_3,
doc_presenter_address_4,
doc_presenter_post_code,
doc_presenter_phone_no,
doc_presenter_mobile_no,
doc_presenter_fax_no,
doc_presenter_ip_address,
doc_presenter_email_address,
doc_presenter_country_name,
doc_ffs_id,
doc_fra_year_no,
doc_fra_month_no,
doc_ffs_status_desc,
doc_ffs_last_changed_date,
doc_size_bytes,
doc_size_desc,
ir_source,
ir_logical_delete_ind,
ir_logical_delete_source,
ir_valid_from,
ir_valid_to,
ir_dup_count
from lab_fcp_raw.coy_raw_company_document ;

compute incremental stats lab_fcp_raw.ptn_coy_raw_company_document;
