CREATE TABLE ${var:target_db}.app_tbltransaction (
FLNGTRANSKEY INT,
FLNGVER INT,
FLNGACCOUNTKEY INT,
FSTRTRANSTYPE VARCHAR(12),
FCURAMOUNT DECIMAL(19,4),
FDTMFILINGPERIOD TIMESTAMP,
FLNGLINKTRANS INT,
FDTMEFFECT TIMESTAMP,
FSTRWHO VARCHAR(20),
FDTMWHEN TIMESTAMP,
insert_object_run_key INT
 ) STORED AS PARQUET;
