hdfs dfs -getfacl hdfs://nameservice1/user/hive/warehouse 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/cas_views 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/dw 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/dw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/dw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/jnl 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/raw 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/raw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/raw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/refined 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/refined_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/refined_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/silver_publish 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/silver_work 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/staging 
hdfs dfs -getfacl hdfs://nameservice1/env/1_dev/hive/work 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/analytics 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/bir 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/cie 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/cora 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/daf 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/data_science 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/daur 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/fcp_raw 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/fcp_raw_cas_views 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/fcp_raw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/fcp_raw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/gst 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/hec 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/heritage2dip 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/intall 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/intsen 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/kyc 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/nzsr4_raw 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/nzsr4_raw_cas_views 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/nzsr4_raw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/nzsr4_raw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/pff 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/platform 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/platform 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/property 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/public 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/r3_assurance 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/teams/rf 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/sfd 
hdfs dfs -getfacl hdfs://nameservice1/env/4_lab/hive/projects/slmrk 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/cas_views 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/dw 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/dw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/dw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/jnl 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/raw 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/raw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/raw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/refined 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/refined_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/refined_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/silver_publish 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/silver_work 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/staging 
hdfs dfs -getfacl hdfs://nameservice1/env/3_prod/hive/work 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/cas_views 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/dw 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/dw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/dw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/jnl 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/raw 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/raw_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/raw_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/refined 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/refined_full_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/refined_restricted_access 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/silver_publish 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/silver_work 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/staging 
hdfs dfs -getfacl hdfs://nameservice1/env/2_test/hive/work 
