hdfs dfs -setfacl -R -m group:ird_pr_r_dadm:rwx hdfs://nameservice1/env/1_dev/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_dadm:rwx hdfs://nameservice1/env/3_prod/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_dadm:rwx hdfs://nameservice1/env/2_test/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/1_dev/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/4_lab/hive/fcp_raw_cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/4_lab/hive/fcp_raw_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/4_lab/hive/fcp_raw_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/4_lab/hive/fcp_raw
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/3_prod/hive/raw
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/3_prod/hive/refined
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/3_prod/hive/staging
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/3_prod/hive/work
hdfs dfs -setfacl -R -m group:ird_pr_r_did:rwx hdfs://nameservice1/env/2_test/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/dw_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/dw_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/dw
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/raw_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/raw_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/raw
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/refined_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/refined_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/refined
hdfs dfs -setfacl -R -m group:ird_pr_r_did:r-x hdfs://nameservice1/env/2_test/hive/staging
hdfs dfs -setfacl -R -m group:ird_pr_r_tst:rwx hdfs://nameservice1/env/2_test/hive/cas_views
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/dw_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/dw_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/dw
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/jnl
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/raw_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/raw_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/raw
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/refined_full_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/refined_restricted_access
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/refined
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/silver_publish
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/silver_work
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/staging
hdfs dfs -setfacl -R -m group:ird_pr_r_ops:r-x hdfs://nameservice1/env/3_prod/hive/work
hdfs dfs -setfacl -R -m group:ird_pr_r_rdq:r-x hdfs://nameservice1/env/1_dev/hive/raw_restricted_access
