hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/analytics
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/bir
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/bronze_publish
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/bronze_work
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/cie
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/cora
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/covid19
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/daf
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/data_science
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/daur
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/fcp_raw
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/fcp_raw_cas_views
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/fcp_raw_full_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/fcp_raw_restricted_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/gst
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/hec
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/heritage2dip
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/idres
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/idres_full_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/idres_restricted_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/intall
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/intsen
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/irs
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/kyc
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/nzsr4_raw
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/nzsr4_raw_full_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/nzsr4_raw_restricted_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/pff
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/platform
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/platform
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/property
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/public
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/r3_assurance
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/teams/rf
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/sfd
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/slmrk
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/4_lab/hive/projects/wii
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/cas_views
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/intel_jnl
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/intel_raw
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/intel_staging
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/jnl
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/raw
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/raw_full_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/raw_restricted_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/refined
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/refined_full_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/refined_restricted_access
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/silver_publish
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/silver_work
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/staging
hdfs dfs -count -q -h  hdfs://ird-prd-002/env/3_prod/hive/work
