USE prod_refined_full_access;

DROP VIEW IF EXISTS account_dim;
DROP VIEW IF EXISTS account_gst_dim;
DROP VIEW IF EXISTS account_inc_dim;
DROP VIEW IF EXISTS account_pay_dim;
DROP VIEW IF EXISTS account_pie_dim;
DROP VIEW IF EXISTS party_account_rel;
DROP VIEW IF EXISTS party_account_rel_type;

CREATE VIEW account_dim AS 
SELECT dip_account_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_dim;

CREATE VIEW account_gst_dim AS 
SELECT dip_account_gst_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       accounting_basis,
       registration_circumstance,
       included_in_prices_flag,
       exempt_supplies_flag,
       exporter_flag,
       importer_flag,
       unpoliced_filer_flag,
       self_invoicer_flag,
       hospice_filer_flag,
       hospice_type,
       hospice_type_desc,
       gst_on_remote_srvcs_flag,
       gst_on_remote_srvcs_type,
       gst_on_remote_srvcs_code,
       gst_zero_rated_fin_srv_flag,
       gst_non_resident_claimant_flag,
       taxable_activity_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_gst_dim;

CREATE VIEW account_inc_dim AS 
SELECT dip_account_inc_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       balance_date,
       zero_tailored_rate_flag,
       trans_tasman_flag,
       agent_non_res_insurer_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_inc_dim;

CREATE VIEW account_pay_dim AS 
SELECT dip_account_pay_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       ir56_flag,
       filing_option,
       filing_option_code,
       payday_filer_flag,
       payday_filer_start_date,
       employer_child_support_flag,
       employer_student_loan_flag,
       kiwisaver_employee_dedn_flag,
       kiwisaver_employer_cntrb_flag,
       esct_flag,
       employer_group,
       employer_group_code,
       payday_variation_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_pay_dim;

CREATE VIEW account_pie_dim AS 
SELECT dip_account_pie_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       pie_type,
       pie_type_code,
       filing_option,
       filing_option_code,
       attribution_period,
       fdr_calc_period,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_pie_dim;

CREATE VIEW party_account_rel AS 
SELECT dip_party_id,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       party_acct_rel_type_code,
       relationship_origin,
       relationship_start_timestamp,
       relationship_end_timestamp,
       dip_confidence_level,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.party_account_rel;

CREATE VIEW party_account_rel_type AS
SELECT relationship_type_code,
       relationship_type_desc
FROM   prod_refined.party_account_rel_type;

USE prod_refined_restricted_access;

DROP VIEW IF EXISTS account_dim;
DROP VIEW IF EXISTS account_gst_dim;
DROP VIEW IF EXISTS account_inc_dim;
DROP VIEW IF EXISTS account_pay_dim;
DROP VIEW IF EXISTS account_pie_dim;
DROP VIEW IF EXISTS party_account_rel;
DROP VIEW IF EXISTS party_account_rel_type;

CREATE VIEW account_dim AS 
SELECT dip_account_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_dim
WHERE  security_level_code = 'STD';

CREATE VIEW account_gst_dim AS 
SELECT dip_account_gst_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       accounting_basis,
       registration_circumstance,
       included_in_prices_flag,
       exempt_supplies_flag,
       exporter_flag,
       importer_flag,
       unpoliced_filer_flag,
       self_invoicer_flag,
       hospice_filer_flag,
       hospice_type,
       hospice_type_desc,
       gst_on_remote_srvcs_flag,
       gst_on_remote_srvcs_type,
       gst_on_remote_srvcs_code,
       gst_zero_rated_fin_srv_flag,
       gst_non_resident_claimant_flag,
       taxable_activity_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_gst_dim
WHERE  security_level_code = 'STD';

CREATE VIEW account_inc_dim AS 
SELECT dip_account_inc_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       balance_date,
       zero_tailored_rate_flag,
       trans_tasman_flag,
       agent_non_res_insurer_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_inc_dim
WHERE  security_level_code = 'STD';

CREATE VIEW account_pay_dim AS 
SELECT dip_account_pay_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       ir56_flag,
       filing_option,
       filing_option_code,
       payday_filer_flag,
       payday_filer_start_date,
       employer_child_support_flag,
       employer_student_loan_flag,
       kiwisaver_employee_dedn_flag,
       kiwisaver_employer_cntrb_flag,
       esct_flag,
       employer_group,
       employer_group_code,
       payday_variation_flag,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_pay_dim
WHERE  security_level_code = 'STD';

CREATE VIEW account_pie_dim AS 
SELECT dip_account_pie_sk,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       account_origin,
       account_key,
       account_ird_number,
       start_account_id,
       start_profile_number,
       start_parent_profile_type,
       start_parent_profile_number,
       heritage_location_number,
       legal_name,
       trading_name,
       account_type,
       account_type_code,
       account_start_date,
       account_ceased_date,
       account_status,
       account_status_code,
       security_level,
       security_level_code,
       cessation_reason,
       cessation_reason_code,
       filing_frequency,
       filing_frequency_code,
       exemption_reason,
       exemption_reason_code,
       exempted_flag,
       account_halt_flag,
       audit_case_active_desc,
       audit_case_active_code,
       audit_case_active_flag,
       stop_mail_desc,
       stop_mail_code,
       stop_mail_flag,
       pie_type,
       pie_type_code,
       filing_option,
       filing_option_code,
       attribution_period,
       fdr_calc_period,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.account_pie_dim
WHERE  security_level_code = 'STD';

CREATE VIEW party_account_rel AS 
SELECT dip_party_id,
       dip_account_id,
       record_effective_timestamp,
       record_expiry_timestamp,
       record_active_flag,
       party_acct_rel_type_code,
       relationship_origin,
       relationship_start_timestamp,
       relationship_end_timestamp,
       dip_confidence_level,
       insert_object_run_key,
       update_object_run_key
FROM   prod_refined.party_account_rel;

CREATE VIEW party_account_rel_type AS
SELECT relationship_type_code,
       relationship_type_desc
FROM   prod_refined.party_account_rel_type;


SELECT '\n\n***************************************\n** DDL Script Completed Successfully **\n***************************************'
