drop table if exists dev_refined.address_dim;

CREATE TABLE dev_refined.address_dim (
     DIP_ADDRESS_SK bigint , 
     DIP_ADDRESS_ID VARCHAR (30), 
     CLEAN_ADDRESS_LIST_FORMAT VARCHAR (255) , 
     PO_BOX VARCHAR (50) , 
     RURAL_DELIVERY VARCHAR (50) , 
     EXTENSION VARCHAR (50) , 
     BUILDING_NAME VARCHAR (50) , 
     STREET_AND_NUMBER VARCHAR (50) , 
     SUBURB VARCHAR (50) , 
     CITY VARCHAR (50) , 
     POSTCODE VARCHAR (50) , 
     ISO_COUNTRY_CODE VARCHAR (10), 
     ISO_COUNTRY_NAME VARCHAR (255) , 
     PHYSICAL_ADDRESS_FLAG CHAR (1) , 
     MAILING_ADDRESS_FLAG CHAR (1) , 
     NZAD_DELIVERY_POINT_ID INTEGER,
     NZAD_MESH_BLOCK_ID INTEGER,
     NZAD_PARCEL_ID INTEGER,
     NZAD_ADDRESS_ID INTEGER,
     LATITUDE_WGS84 DECIMAL (13,6) , 
     LONGITUDE_WGS84 DECIMAL (13,6) , 
     LATITUDE_NZGD2000 DECIMAL (13,6) , 
     LONGITUDE_NZGD2000 DECIMAL (13,6) , 
     NZAD_REGIONAL_COUNCIL_NAME VARCHAR (50) , 
     NZAD_TERRITORIAL_AUTHORITY_NAME VARCHAR (50) , 
     NZAD_RECORD_USAGE_ID INTEGER,
     NZAD_RECEIVES_MAIL_DELIVERY_FLAG CHAR (1) , 
     ADDRESS_VERIFIED_FLAG CHAR (1) , 
     ADDRESS_VERIFICATION_CODE VARCHAR (50) , 
     DATA_QUALITY_PERCENT DECIMAL (5,2) , 
     DATA_QUALITY_CODE VARCHAR (10),
     insert_object_run_key	int	,
update_object_run_key	int	
)
STORED AS parquet;

create table  dev_refined.rfn_address_dim_d stored as parquet
as
select * from  dev_refined.address_dim ;


drop table if exists dev_refined.rfn_contact_address_sk_map;

CREATE TABLE dev_refined.rfn_contact_address_sk_map (
     dip_address_sk bigint , 
     listformataddress VARCHAR (256),
     insert_object_run_key	int	
 )
 stored as parquet;



CREATE TABLE ACCOUNT_ADDRESS_RELATIONSHIP 
    (
     DIP_ACCOUNT_ID VARCHAR (30), 
     DIP_ADDRESS_ID VARCHAR (30), 
     ACCOUNT_ADDRESS_RELATIONSHIP_TYPE_CODE VARCHAR (10), 
     RELATIONSHIP_START_TIMESTAMP TIMESTAMP, 
     RELATIONSHIP_END_TIMESTAMP TIMESTAMP, 
     ADDRESS_REDIRECTION_FLAG CHAR (1)
    )
GO


CREATE TABLE ACCOUNT_ADDRESS_RELATIONSHIP_TYPE 
    (
     ACCOUNT_ADDRESS_RELATIONSHIP_TYPE_CODE VARCHAR (10), 
     ACCOUNT_ADDRESS_RELATIONSHIP_TYPE_DESCRIPTION VARCHAR (50) 
    )
GO


CREATE TABLE ISO_COUNTRY_LKP 
    (
     ISO_COUNTRY_CODE VARCHAR (10), 
     ISO_COUNTRY_NAME VARCHAR (50) 
    )
GO


CREATE TABLE PARTY_ADDRESS_RELATIONSHIP 
    (
     DIP_PARTY_ID VARCHAR (30), 
     DIP_ADDRESS_ID VARCHAR (30), 
     PARTY_ADDRESS_RELATIONSHIP_TYPE_CODE VARCHAR (10), 
     RELATIONSHIP_START_TIMESTAMP TIMESTAMP, 
     RELATIONSHIP_END_TIMESTAMP TIMESTAMP
    )
GO


CREATE TABLE PARTY_ADDRESS_RELATIONSHIP_TYPE 
    (
     PARTY_ADDRESS_RELATIONSHIP_TYPE_CODE VARCHAR (10), 
     PARTY_ADDRESS_RELATIONSHIP_TYPE_DESCRIPTION VARCHAR (50) 
    )
GO


CREATE TABLE SOURCE_ADDRESS_CLEAN_ADDRESS_LKP 
    (
     DIP_SOURCE_ADDRESS_ID VARCHAR (30), 
     DIP_ADDRESS_ID VARCHAR (30), 
     SOURCE_ADDRESS_LIST_FORMAT VARCHAR (255), 
     ATTENTION VARCHAR (255) , 
     ADDITIONAL_TEXT VARCHAR (255) 
    )
GO
