CREATE VIEW ${var:view_db}.dss_spk2ir_questions AS
SELECT z.QUESTION_ID, z.CALL_NUMBER_CODE, z.QUESTION_CODE, z.QUESTION_START_TIME, z.QUESTION_END_TIME, z.COMPONENT_CODE, z.`STATUS`, z.EDW_LOAD_DATE, z.RUN_ID, z.QUESTION_DURATION, z.QUESTION_ACCESS_COUNT, z.QUESTION_STATUS_CODE, z.CALL_LEG, z.insert_object_run_key FROM ${var:source_db}.dss_spk2ir_questions z;
