scp dss_returns_keypoints_ir348-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir422-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir44-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4f-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4j-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4k-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4p-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir66n-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir66a-full.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir348-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir422-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir44-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4f-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4j-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4k-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir4p-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir66n-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
scp dss_returns_keypoints_ir66a-restricted.ddl ird26au.vsp.sas.com:/home/ird0qal
