--create journal table
create table ${var:db_env}_jnl.${var:table_name}
(
flngQueueKey INT,                                                                                                                   
flngVer INT,                                                                                                                        
flngVerLast INT,                                                                                                                    
flngQueueId INT,                                                                                                                    
flngOrder INT,                                                                                                                      
fstrName VARCHAR(510),                                                                                                              
fstrOwner VARCHAR(20),                                                                                                              
fstrDescription VARCHAR(2000),                                                                                                      
flngCrmKey INT,                                                                                                                     
fintNotificationType SMALLINT,                                                                                                      
fblnInteractive SMALLINT,                                                                                                           
flngWeight INT,                                                                                                                     
flngReminderDelay INT,                                                                                                              
fstrUnitType VARCHAR(24),                                                                                                           
fdtmCommence TIMESTAMP,                                                                                                             
fdtmCease TIMESTAMP,                                                                                                                
fblnActive SMALLINT,                                                                                                                
fstrWho VARCHAR(20),                                                                                                                
fdtmWhen TIMESTAMP,                          
batch_key INT
)
stored as parquet;

insert into ${var:db_env}_jnl.${var:table_name}
(
flngQueueKey,
flngVer,
flngVerLast,
flngQueueId,
flngOrder,
fstrName,
fstrOwner,
fstrDescription,
flngCrmKey,
fintNotificationType,
fblnInteractive,
flngWeight,
flngReminderDelay,
fstrUnitType,
fdtmCommence,
fdtmCease,
fblnActive,
fstrWho,
fdtmWhen,
batch_key)
select 
flngQueueKey,
flngVer,
flngVerLast,
flngQueueId,
flngOrder,
fstrName,
fstrOwner,
fstrDescription,
flngCrmKey,
cast(0 as smallint),
fblnInteractive,
flngWeight,
0,
cast('' as varchar(24)),
fdtmCommence,
fdtmCease,
fblnActive,
fstrWho,
fdtmWhen,
batch_key
from ${var:db_env}_dw.${var:db_env}_jnl_${var:table_name}_${var:table_suffix}
;

insert into ${var:db_name}.${var:table_name}
(
flngQueueKey,
flngVer,
flngVerLast,
flngQueueId,
flngOrder,
fstrName,
fstrOwner,
fstrDescription,
flngCrmKey,
fintNotificationType,
fblnInteractive,
flngWeight,
flngReminderDelay,
fstrUnitType,
fdtmCommence,
fdtmCease,
fblnActive,
fstrWho,
fdtmWhen,
record_effective_timestamp,
record_expiry_timestamp,
record_active_flag,
record_deleted_flag,
insert_object_run_key,
update_object_run_key)
select
flngQueueKey,
flngVer,
flngVerLast,
flngQueueId,
flngOrder,
fstrName,
fstrOwner,
fstrDescription,
flngCrmKey,
cast(0 as smallint),
fblnInteractive,
flngWeight,
0,
null,
fdtmCommence,
fdtmCease,
fblnActive,
fstrWho,
fdtmWhen,
record_effective_timestamp,
record_expiry_timestamp,
record_active_flag,
record_deleted_flag,
insert_object_run_key,
update_object_run_key
from ${var:db_env}_dw.${var:db_name}_${var:table_name}_${var:table_suffix}
;

