drop table if exists  mobject;
create table mobject (
OBJECT_KEY bigint,
SYSTEM_SCHEMA_KEY bigint,
TARGET_OBJECT_NAME varchar(30),
OBJECT_SHORT_NAME varchar(25),
TARGET_DB varchar(30),
SOURCE_OBJECT_NAME varchar(30),
SOURCE_OBJECT_TYPE varchar(5),
SAS_LIB_REF varchar(30),
PK_COLUMN_NAMES varchar(500),
NK_COLUMN_NAMES varchar(500),
EXCLUDED_COLUMNS string,
LOAD_PATTERN_NAME varchar(30),
SENSITIVE_DATA_FLAG varchar(1),
RETENTION_KEY bigint,
CUSTOM_SQL string,
CHANGE_CAPTURE_TIMESTAMP_COLUMN varchar(50),
HISTORY_LOADED_FROM_TDW varchar(2),
HISTORY_TYPE varchar(5),
EFFECTIVE_FROM_TIMESTAMP_COLUMN varchar(50),
EFFECTIVE_TO_TIMESTAMP_COLUMN varchar(50),
EFFECTIVE_TIMESTAMP_GRAIN varchar(30),
PURGE_GRAIN varchar(30),
DUPLICATION_TIMESTAMP_GRAIN varchar(30),
LAYER varchar(15),
PARTITION_KEY varchar(4000),
CREATED_BY varchar(10),
CREATED_ON timestamp,
UPDATED_BY varchar(10),
UPDATED_ON timestamp,
INGESTION_MODE varchar(10),
SECURITY_NOTES string
) row format delimited fields terminated by '\001' stored as textfile;
