CREATE TABLE object_run_lq (
  object_run_key INT,
  target_object_name STRING,
  object_key INT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  status STRING,
  status_message STRING,
  records_read BIGINT,
  records_written BIGINT,
  object_log_name STRING,
  object_prg_name STRING,
  ingestion_mode STRING,
  prev_high_water_mark_value TIMESTAMP,
  high_water_mark_value_jnl TIMESTAMP,
  high_water_mark_value TIMESTAMP,
  load_pattern_name STRING,
  task1 STRING,
  task1_start_time TIMESTAMP,
  task1_end_time TIMESTAMP,
  task2 STRING,
  task2_start_time TIMESTAMP,
  task2_end_time TIMESTAMP,
  task3 STRING,
  task3_start_time TIMESTAMP,
  task3_end_time TIMESTAMP,
  task4 STRING,
  task4_start_time TIMESTAMP,
  task4_end_time TIMESTAMP,
  task5 STRING,
  task5_start_time TIMESTAMP,
  task5_end_time TIMESTAMP,
  task6 STRING,
  task6_start_time TIMESTAMP,
  task6_end_time TIMESTAMP,
  task7 STRING,
  task7_start_time TIMESTAMP,
  task7_end_time TIMESTAMP,
  task8 STRING,
  task8_start_time TIMESTAMP,
  task8_end_time TIMESTAMP,
  task9 STRING,
  task9_start_time TIMESTAMP,
  task9_end_time TIMESTAMP,
  task10 STRING,
  task10_start_time TIMESTAMP,
  task10_end_time TIMESTAMP,
  task11 STRING,
  task11_start_time TIMESTAMP,
  task11_end_time TIMESTAMP,
  run_date_time TIMESTAMP,
  insert_object_run_key INT,
  primary key (object_run_key)
)
PARTITION BY HASH PARTITIONS 2
STORED AS KUDU
;

